trigger:
  branches:
    include:
      - main

variables:
  - group: github_Credi

stages:

- stage: SyncToGitHub
  displayName: 'Sync to GitHub'
  jobs:
  - job: MirrorJob
    pool:
      name: Default
    steps:
    - checkout: self
      clean: true
      fetchDepth: 0
    - script: |
        git config --global user.email "m_moukouba@yahoo.fr"
        git config --global user.name "Moukouba"
        git remote remove github || echo "remote not found"
        git remote add github https://$(GITHUB_PAT)@github.com/Moukouba/$(Build.Repository.Name).git
        git push github HEAD:main --force
      displayName: 'Push to GitHub'

- stage: TrainModel
  displayName: 'Train on Azure ML'
  dependsOn: SyncToGitHub
  jobs:
  - job: SubmitTraining
    pool:
      name: Default
    steps:
    - task: AzureCLI@2
      displayName: 'Submit Azure ML Training Job'
      inputs:
        azureSubscription: 'mlops_anomaly'  # ← name from Step 4
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az extension add -n ml
          az ml job create \
            --file jobs/train.yml \
            --workspace-name $(AML_WORKSPACE) \
            --resource-group $(AML_RESOURCE_GROUP)