# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  paths:
    include:
      - infra

pool:
  name: Default

variables:
  - group: mlops-azure-components

stages:
  - stage: BootstrapAzureInfra
    displayName: "Provision Core Azure Infrastructure"
    jobs:
      - job: Setup
        displayName: "Create Workspace, Compute, Dataset, Environment"
        steps:

          - task: AzureCLI@2
            displayName: "Step 0 - Install Azure ML extension"
            inputs:
              azureSubscription: mlops_anomaly
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az extension add --name ml

          - task: AzureCLI@2
            displayName: "Step 1 - Create Resource Group"
            inputs:
              azureSubscription: mlops_anomaly
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az group create \
                  --name $(RESOURCE_GROUP) \
                  --location $(LOCATION)

          - task: AzureCLI@2
            displayName: "Step 2 - Create ML Workspace"
            inputs:
              azureSubscription: mlops_anomaly
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az ml workspace create \
                  --name $(WORKSPACE) \
                  --resource-group $(RESOURCE_GROUP) \
                  --location $(LOCATION)

          - task: AzureCLI@2
            displayName: "Step 3 - Create Key Vault & Upload SSL Cert and Key"
            inputs:
              azureSubscription: mlops_anomaly
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az keyvault create \
                  --name $(KEY_VAULT_NAME) \
                  --resource-group $(RESOURCE_GROUP)
                az keyvault secret set \
                  --vault-name $(KEY_VAULT_NAME) \
                  --name ssl-cert \
                  --file $(SSL_CERT_PATH)
                az keyvault secret set \
                  --vault-name $(KEY_VAULT_NAME) \
                  --name ssl-key \
                  --file $(SSL_KEY_PATH)

          - task: AzureCLI@2
            displayName: "Step 4 - Create Azure ML Compute Cluster"
            inputs:
              azureSubscription: mlops_anomaly
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az ml compute create \
                  --name $(COMPUTE_NAME) \
                  --resource-group $(RESOURCE_GROUP) \
                  --type AmlCompute \
                  --size Standard_DS3_v2 \
                  --min-instances 0 \
                  --max-instances 1 \
                  --idle-time-before-scale-down 120 \
                  --workspace-name $(WORKSPACE)

          - task: AzureCLI@2
            displayName: "Step 5 - Upload Training Images to ML Dataset"
            inputs:
              azureSubscription: mlops_anomaly
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                echo "Uploading from: $(DATA_ANO_DIR)"
                az ml data create \
                  --name anomaly-images \
                  --type uri_folder \
                  --path $(DATA_ANO_DIR) \
                  --description "Training + test + ground truth images for anomaly detection" \
                  --workspace-name $(WORKSPACE) \
                  --resource-group $(RESOURCE_GROUP)

          - task: AzureCLI@2
            displayName: "Step 6 - Create Training Environment"
            inputs:
              azureSubscription: mlops_anomaly
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az ml environment create \
                  --name mlops_anomavision \
                  --image mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:latest \
                  --conda-file $(Build.SourcesDirectory)/deployment/environment.yml \
                  --resource-group $(RESOURCE_GROUP) \
                  --workspace-name $(WORKSPACE)