trigger:
  branches:
    include:
      - main

variables:
  - group: github_Credi

stages:
- stage: SyncToGitHub
  displayName: 'Sync Azure DevOps Repo to GitHub'
  jobs:
  - job: MirrorJob
    displayName: 'Mirror to GitHub'
    pool:
      name: Default
    steps:
    - checkout: self
      clean: true
      fetchDepth: 0

    - script: |
        set -euo pipefail

        git config --global user.email "m_moukouba@yahoo.fr"
        git config --global user.name "Moukouba"

        git remote remove github || true
        git remote add github https://github.com/Moukouba/$(Build.Repository.Name).git

        git config --global credential.helper store
        echo "https://$(GITHUB_PAT):x-oauth-basic@github.com" > ~/.git-credentials

        git push github HEAD:main --force-with-lease
      displayName: 'Push to GitHub'
