trigger:
  branches:
    include:
      - main

variables:
  - group: github_Credi

stages:
- stage: SyncToGitHub
  displayName: 'Sync Azure DevOps Repo to GitHub'
  jobs:
  - job: MirrorJob
    displayName: 'Mirror to GitHub'
    pool:
      name: Default
    steps:
    - checkout: self
      clean: true
      fetchDepth: 0   # IMPORTANT: full history

    - script: |
        git config --global user.email "m_moukouba@yahoo.fr"
        git config --global user.name "Moukouba"

        git remote remove github || echo remote not found
        git remote add github https://$(GITHUB_PAT)@github.com/Moukouba/$(Build.Repository.Name).git

        git push github HEAD:main --force
      displayName: 'Push to GitHub'
