name: Sync to Azure DevOps

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # full history

      - name: Push to Azure DevOps
        run: |
          git config --global user.email "m_moukouba@yahoo.fr"
          git config --global user.name "Moukouba"

          git remote add devops https://$(AZURE_DEVOPS_PAT)@dev.azure.com/mmoukouba/anodetect/_git/industrial_anodetect_mlops

          git push devops HEAD:main --force-with-lease